name = "lux-mgfx"

[[package]]
id = "@lux/mgfx"
version = "0.1.0"
path = "lux-mgfx/lux/mgfx"
license = "Lux-MGFX-NC"
depends = [
  "@lux/mgfx/capabilities >=0.1 <0.2",
  "@lux/mgfx/commands >=0.1 <0.2",
  "@lux/mgfx/frame >=0.1 <0.2",
  "@lux/mgfx/geometry >=0.1 <0.2",
  "@lux/mgfx/materials >=0.1 <0.2",
  "@lux/mgfx/paint >=0.1 <0.2",
  "@lux/mgfx/primitives >=0.1 <0.2",
  "@lux/mgfx/profiler >=0.1 <0.2",
  "@lux/mgfx/roundrect >=0.1 <0.2",
  "@lux/mgfx/shaderpack >=0.1 <0.2",
  "@lux/mgfx/style >=0.1 <0.2",
  "@lux/mgfx/text >=0.1 <0.2",
  "@lux/mgfx/widgets >=0.1 <0.2",
]

[[package]]
id = "@lux/mgfx/capabilities"
version = "0.1.0"
path = "lux-mgfx/lux/mgfx/capabilities"
license = "Lux-MGFX-NC"
depends = ["@lux/compile/macro >=0.1 <0.2", "@lux/mgfx/style >=0.1 <0.2"]

[[package]]
id = "@lux/mgfx/commands"
version = "0.1.0"
path = "lux-mgfx/lux/mgfx/commands"
license = "Lux-MGFX-NC"
depends = ["@lux/compile/macro >=0.1 <0.2"]

[[package]]
id = "@lux/mgfx/console"
version = "0.1.0"
path = "lux-mgfx/lux/mgfx/console"
license = "Lux-MGFX-NC"
depends = [
  "@lux/mgfx/materials >=0.1 <0.2",
]

[[package]]
id = "@lux/mgfx/demo"
version = "0.1.0"
path = "lux-mgfx/lux/mgfx/demo"
license = "Lux-MGFX-NC"
depends = [
  "@lux/mgfx >=0.1 <0.2",
]

[[package]]
id = "@lux/mgfx/frame"
version = "0.1.0"
path = "lux-mgfx/lux/mgfx/frame"
license = "Lux-MGFX-NC"

[[package]]
id = "@lux/mgfx/geometry"
version = "0.1.0"
path = "lux-mgfx/lux/mgfx/geometry"
license = "Lux-MGFX-NC"
depends = ["@lux/mgfx/style >=0.1 <0.2"]

[[package]]
id = "@lux/mgfx/materials"
version = "0.1.0"
path = "lux-mgfx/lux/mgfx/materials"
license = "Lux-MGFX-NC"
depends = ["@lux/mgfx/shaderpack >=0.1 <0.2"]

[[package]]
id = "@lux/mgfx/paint"
version = "0.1.0"
path = "lux-mgfx/lux/mgfx/paint"
license = "Lux-MGFX-NC"
depends = [
  "@lux/mgfx/frame >=0.1 <0.2",
  "@lux/mgfx/geometry >=0.1 <0.2",
  "@lux/mgfx/style >=0.1 <0.2",
]

[[package]]
id = "@lux/mgfx/primitives"
version = "0.1.0"
path = "lux-mgfx/lux/mgfx/primitives"
license = "Lux-MGFX-NC"
depends = [
  "@lux/mgfx/geometry >=0.1 <0.2",
  "@lux/mgfx/roundrect >=0.1 <0.2",
  "@lux/mgfx/style >=0.1 <0.2",
]

[[package]]
id = "@lux/mgfx/profiler"
version = "0.1.0"
path = "lux-mgfx/lux/mgfx/profiler"
license = "Lux-MGFX-NC"

[[package]]
id = "@lux/mgfx/roundrect"
version = "0.1.0"
path = "lux-mgfx/lux/mgfx/roundrect"
license = "Lux-MGFX-NC"
depends = [
  "@lux/mgfx/geometry >=0.1 <0.2",
  "@lux/mgfx/style >=0.1 <0.2",
]

[[package]]
id = "@lux/mgfx/shaderpack"
version = "0.1.0"
path = "lux-mgfx/lux/mgfx/shaderpack"
license = "Lux-MGFX-NC"

[[package]]
id = "@lux/mgfx/style"
version = "0.1.0"
path = "lux-mgfx/lux/mgfx/style"
license = "Lux-MGFX-NC"

[[package]]
id = "@lux/mgfx/text"
version = "0.1.0"
path = "lux-mgfx/lux/mgfx/text"
license = "Lux-MGFX-NC"
depends = [
  "@lux/mgfx/frame >=0.1 <0.2",
  "@lux/mgfx/style >=0.1 <0.2",
]

[[package]]
id = "@lux/mgfx/widgets"
version = "0.1.0"
path = "lux-mgfx/lux/mgfx/widgets"
license = "Lux-MGFX-NC"
depends = [
  "@lux/mgfx/geometry >=0.1 <0.2",
  "@lux/mgfx/paint >=0.1 <0.2",
  "@lux/mgfx/primitives >=0.1 <0.2",
  "@lux/mgfx/roundrect >=0.1 <0.2",
  "@lux/mgfx/style >=0.1 <0.2",
  "@lux/mgfx/text >=0.1 <0.2",
]

[[package]]
id = "@lux/mgfx/wheel_demo"
version = "0.1.0"
path = "lux-mgfx/lux/mgfx/wheel_demo"
license = "Lux-MGFX-NC"
depends = [
  "@lux/mgfx >=0.1 <0.2",
]

[[source]]
package = "@lux/compile/macro"
github = "TimeWatcher/lux-packages"
